apiVersion: v1
kind: ServiceAccount
metadata:
  name: debug-service-account  # Tạo ServiceAccount

---
apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  serviceAccountName: debug-service-account  # Gắn ServiceAccount vào Pod
  containers:
  - name: debug-container
    image: busybox  # Sử dụng busybox image cho mục đích debug
    command: ["sleep", "3600"]  # Container sẽ chạy lệnh sleep trong 3600 giây (1 giờ)
    stdin: true
    tty: true