apiVersion: apps/v1
kind: Deployment # Chỉ định loại tài nguyên, ở đây là "Deployment"
metadata: # Chứa thông tin về tài nguyên
  name: echo-server-deployment
  labels: # Các nhãn được gắn với tài nguyên này, cho phép bạn định danh và phân nhóm các tài nguyên.
    app: echo-server
spec:
  replicas: 2
  selector: #  Xác định cách chọn Pod mà Deployment quản lý
    matchLabels: # Các nhãn được sử dụng để xác định các Pod thuộc về Deployment.
      # Trong trường này, nó sử dụng nhãn "app: nginx" để lựa chọn các Pod có nhãn này
      # Tức là sẽ dựa vào label này của Pod để biết đang có bao nhiêu instance từ đó điều chỉnh như mong muốn (desire state)
      app: echo-server
  template: # Định nghĩa template cho các Pod sẽ được triển khai
    metadata: # Chứa thông tin về template Pod
      labels: # Các nhãn được gắn với template Pod, trong trường này có nhãn "app: nginx".
        app: echo-server
    spec: # Xác định cấu hình cho template Pod, bao gồm các container bên trong nó
      containers:
        - name: echo-server
          image: kicbase/echo-server:1.0
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.5"
---
kind: Service
apiVersion: v1
metadata:
  name: echo-server-service
spec:
  selector:
    app: echo-server
  ports:
    # By default, and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-server-ingress
  annotations: # Annotations cho phép bạn lưu trữ các dữ liệu không xác định trước
    # Tùy từng ingress controller khác nhau mà phần này config sẽ khác nhau
    # Trong trường hợp này, là rewrite lại mọi path sang path / ở application
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /foo
            pathType: Prefix
            backend:
              service:
                name: echo-server-service
                port:
                  number: 8080