apiVersion: apps/v1
kind: Deployment # Chỉ định loại tài nguyên, ở đây là "Deployment"
metadata: # Chứa thông tin về tài nguyên
  name: echo-server-deployment
  labels: # Các nhãn được gắn với tài nguyên này, cho phép bạn định danh và phân nhóm các tài nguyên.
    app: echo-server
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: echo-server
  template:
    metadata: 
      labels: 
        app: echo-server
    spec: # Xác định cấu hình cho template Pod, bao gồm các container bên trong nó
      containers:
        - name: echo-server
          image: kicbase/echo-server:1.0
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.5"
---
kind: Service
apiVersion: v1
metadata:
  name: echo-server-service
spec:
  selector:
    app: echo-server
  ports:
    # By default, and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
